import { useApi } from './useApi';

const { get, post, put, del, patch } = useApi();

export const apiServices = {
  postEventProcessCreate: ({ body: { event_type, material_id, activity_code }, ...options }) => post(`/event-process-create`, { event_type, material_id, activity_code }, options),
  postEventProcessEnd: ({ params: { eventId }, ...options }) => post(`/event-process-end/${eventId}`, {}, options),
  putEventProcessUpdateAttributes: ({ body: { notes, scrap_flag, activity_code, material_code, ply, operator_shift, loaded_schedule, machine_operator, supplementary_flag }, params: { eventId }, ...options }) => put(`/event-process-update-attributes/${eventId}`, { notes, scrap_flag, activity_code, material_code, ply, operator_shift, loaded_schedule, machine_operator, supplementary_flag }, options),
  getEventHistoryAll: ({ params: { event_type }, ...options }) => get(`/event-history-all/${event_type}`, options),
  getEventHistoryEntity: ({ params: { event_type }, ...options }) => get(`/event-history-entity/${event_type}`, options),
  getCapturedValues: ({ params: { capture_type }, ...options }) => get(`/captured-values/${capture_type}`, options),
  postEventApply: ({ params: { event_type, event_id }, ...options }) => post(`/event-apply/${event_type}/${event_id}`, {}, options),
  getAllSchedules: ({ params: { schedule_type }, ...options }) => get(`/all-schedules/${schedule_type}`, options),
  getAllSchedulesEntity: ({ params: { schedule_type }, ...options }) => get(`/all-schedules-entity/${schedule_type}`, options),
  getLoadedScheduleData: ({ ...options }) => get(`/loaded-schedule-data`, options),
  getLoadSchedule: ({ params: { schedule_id }, ...options }) => get(`/load-schedule/${schedule_id}`, options),
  getUnloadSchedule: ({ ...options }) => get(`/unload-schedule`, options),
  postSchedulesBatchUpload: ({ body: { sql_script }, params: { schedule_type }, ...options }) => post(`/schedules-batch-upload/${schedule_type}`, { sql_script }, options),
  postSchedulesBatchReplace: ({ body: { sql_script }, params: { schedule_type }, ...options }) => post(`/schedules-batch-replace/${schedule_type}`, { sql_script }, options),
  putModifyScheduleData: ({ body: { schedule_category, planned_start_time, planned_finish_time, schedule_data, notes }, params: { schedule_id }, ...options }) => put(`/modify-schedule-data/${schedule_id}`, { schedule_category, planned_start_time, planned_finish_time, schedule_data, notes }, options),
  postCreateScheduleData: ({ body: { schedule_category, planned_start_time, planned_finish_time, schedule_data, notes }, ...options }) => post(`/create-schedule-data`, { schedule_category, planned_start_time, planned_finish_time, schedule_data, notes }, options),
  deleteDeleteScheduleData: ({ params: { schedule_id }, ...options }) => del(`/delete-schedule-data/${schedule_id}`, options),
  getHealthCheck: ({ ...options }) => get(`/health-check`, options),
  getDataReferenceAll: ({ params: { reference_category }, ...options }) => get(`/data-reference-all/${reference_category}`, options),
  getDataReferenceOne: ({ params: { reference_category }, ...options }) => get(`/data-reference-one/${reference_category}`, options),
  getAccountValidate: ({ ...options }) => get(`/account-validate`, options),
  postAccountLogin: ({ body: { username, password, role, selectedEntityId, selectedShiftId }, ...options }) => post(`/account-login`, { username, password, role, selectedEntityId, selectedShiftId }, options),
  postAccountLogout: ({ ...options }) => post(`/account-logout`, {}, options),
  putAccountUpdate: ({ body: { fullname, role, username, password, status }, params: { accountId }, ...options }) => put(`/account-update/${accountId}`, { fullname, role, username, password, status }, options),
  postCreateReference: ({ body: { key, value, description }, ...options }) => post(`/create-reference`, { key, value, description }, options),
  postGetAllReference: ({ body: { pattern }, ...options }) => post(`/get-all-reference`, { pattern }, options),
  postDeleteReference: ({ body: { key }, ...options }) => post(`/delete-reference`, { key }, options),
  putUpdateReference: ({ body: { key, value, description }, ...options }) => put(`/update-reference`, { key, value, description }, options),
  postGetOneReference: ({ body: { key }, ...options }) => post(`/get-one-reference`, { key }, options),
  postCreateEventprocess: ({ body: { key, notes, scrap_flag, activities, material, ply, supplementary_flag }, ...options }) => post(`/create-event/process`, { key, notes, scrap_flag, activities, material, ply, supplementary_flag }, options),
  postUpdateEventprocess: ({ body: { notes, scrap_flag, activities, material, ply, operator_shift, loaded_schedule, machine_operator, supplementary_flag }, ...options }) => post(`/update-event/process`, { notes, scrap_flag, activities, material, ply, operator_shift, loaded_schedule, machine_operator, supplementary_flag }, options),
  postREDisscheduleget: ({ body: { pattern }, ...options }) => post(`/REDis/schedule/get-populated`, { pattern }, options),
  postREDisscheduleset: ({ body: { id, schedule_category, planned_start_time, planned_finish_time, schedule_status, actual_start_time, actual_finish_time, schedule_data, notes, created_on, updated_on }, ...options }) => post(`/REDis/schedule/set`, { id, schedule_category, planned_start_time, planned_finish_time, schedule_status, actual_start_time, actual_finish_time, schedule_data, notes, created_on, updated_on }, options),
  postREDisscheduleremove: ({ body: { pattern }, ...options }) => post(`/REDis/schedule/remove`, { pattern }, options),
};
